Fix non-passive event listeners issue and add a updated version number
jquery/jquery-mousewheel pull request #215
Opened 2020-12-23 16:37 UTC by ayumi-cloud

Relates to (my old account) issue found here: https://github.com/jquery/jquery-mousewheel/issues/202

Have tested this and works fine.

2021-09-27 07:30 UTC, SNDST00M commented
@mgol another one to review after #127

2021-09-27 11:18 UTC, mgol requested changes
This change is essentially a noop but it doesn't work in IE which has no support for passive listeners. The upstream jQuery also doesn't use a pattern like this so I'm not in favor.

@dmethvin what do you think?

2021-09-27 11:20 UTC, SNDST00M commented
Could a compatibility layer be added for IE?

2021-09-27 11:27 UTC, mgol commented
Yes, it could, but it'd still be adding lots of bytes just to silence browser warnings without any actual change in behavior. If we were doing that for jQuery as well it'd make sense but I'm not sure about doing it just in this plugin, diverging from the upstream.

2021-09-27 11:28 UTC, SNDST00M commented
Okay, so the ideal thing to do is icebox this and have passive event listeners adopted in JQ core?

2021-09-27 12:07 UTC, mgol commented
Yes, I think that’s the best option here.--
Michał Gołębiowski-Owczarek

2022-04-20 13:16 UTC, summercms commented
@mgol Internet Explorer 11 desktop application will be retired and go out of support on June 15, 2022. Therefore this repo shouldn't continue to support ie11.

Link: https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/

2022-04-20 13:54 UTC, mgol commented
This project will most likely keep following the browser support policy of jQuery and there are no plans to drop IE 11 support there yet.

2025-03-17 17:36 UTC, nagyimre1980 commented
next release should include this

2025-07-14 17:00 UTC, closed without merging